In [40]:
from pathlib import Path
import sys
import os

PROJECT_ROOT = Path.cwd().parent

import pandas as pd

import src.constants as Con

In [41]:
from src.data_paths import (
    EXPERIMENT_TEXT_COMPLETED_PATH,

    DATA_DIR,
    EXPERIMENT_DIR
)

In [42]:
texts_df = pd.read_csv(EXPERIMENT_DIR / "adv_texts_with_ids.csv", encoding="utf-8")
texts_df

,text_id_with_q,paragraph,question,answer_A,answer_B,answer_C,answer_D,rephrased_answer_A,onestopqa_question_id,article_id,paragraph_id,difficulty_level,article_batch,article_title
0,1_0_Adv_1_0,Leading water scientists have issued one of th...,"According to Malik Falkenmark's report, what w...",There will not be sufficient water to grow eno...,"By 2050, nine billion people will not have eno...","By 2050, animal-based protein consumption will...",Obesity rates around the world will rise,There won't be enough water to grow food for a...,0,0,1,Adv,1,NaN
1,1_0_Adv_2_0,"""There will be just enough water if the propor...",Which factor led to the increase in the price ...,Unfavorable weather conditions in different lo...,Instability of the international financial mar...,Warnings of water scarcity by Oxfam and the UN,Global warming,Bad weather in different locations on the planet,0,0,2,Adv,1,NaN
2,1_10_Adv_1_0,"Agios Efstratios is so remote, so forgotten by...",What event dramatically reduced the quality of...,The financial crisis that occurred in the country,A storm in the northern Aegean sea that devast...,The removal of ATM machines from the island,The installment of a new government,The national economic crisis,0,10,1,Adv,1,The Greek Island Where Time Is Running Out
3,1_10_Adv_1_1,"Agios Efstratios is so remote, so forgotten by...",What was true about tourism in Agios Efstratio...,A small number of tourists visited Agios Efstr...,Tourists overcrowded Agios Efstratios,Agios Efstratios was so remote that tourists w...,Many tourism agencies gave awards to Agios Efs...,A relatively small group of tourists visited t...,1,10,1,Adv,1,The Greek Island Where Time Is Running Out
4,1_10_Adv_1_2,"Agios Efstratios is so remote, so forgotten by...",Are there many hotels in Agios Efstratios?,"No, as there are only a small number of rooms ...","No, the beaches are empty of hotels","Yes, they are all in remote locations","Yes, the island has several 5-star resorts","No, the accommodation is limited to a small nu...",2,10,1,Adv,1,The Greek Island Where Time Is Running Out
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,3_9_Adv_3_1,SOHAY also runs sessions for parents and emplo...,What do Zhorna's brothers do?,They are both employed so that they can make m...,"One works at a restaurant and a club, and the ...",They try their best to not drop out of school ...,They help Zhorna with her homework after school,Both brothers have jobs to help their parents ...,1,9,3,Adv,3,Bangladeshi Organization Delivers a Lesson on ...
488,3_9_Adv_3_2,SOHAY also runs sessions for parents and emplo...,Why do Zhorna's brothers both work instead of ...,Their family is reliant on their salaries to m...,They prefer helping their parents,They found it too difficult to adapt to school,The nearest school is too far to commute to daily,Their family depends on the money they earn,2,9,3,Adv,3,Bangladeshi Organization Delivers a Lesson on ...
489,3_9_Adv_4_0,"In 2015, SOHAY helped 1,540 children to leave ...",What statistic does UNICEF provide about child...,1.3 million children are employed in unsafe wo...,4.7 million children are unable to attend school,"1,540 children were able to leave risky work i...",The children labor rates in Bangladesh are hig...,1.3 million children work in hazardous industries,1,9,4,Adv,3,Bangladeshi Organization Delivers a Lesson on ...
490,3_9_Adv_4_1,"In 2015, SOHAY helped 1,540 children to leave ...",What did SOHAY do in 2015?,"Assisted 2,125 children in attending school in...","Provided funds for 1,540 children in danger of...",Collaborated with UNICEF to reduce child labor,"Provided free classes for 3,000 children","Assisted 2,125 children in going to school rat...",0,9,4,Adv,3,Bangladeshi Organization Delivers a Lesson on ...
491,3_9_Adv_4_2,"In 2015, SOHAY helped 1,540 children to leave ...",How many children did SOHAY help leave work in...,"1,540","2,125",1.3 million,"10,000","1,540",2,9,4,Adv,3,Bangladeshi Organization Delivers a Lesson on ...

In [43]:
from ftfy import fix_text
cols_to_repair = [
    "paragraph",
    "question",
    "answer_A",
    "answer_B",
    "answer_C",
    "answer_D",
    "rephrased_answer_A",
    "article_title"
]

def repair_mojibake(value):
    if isinstance(value, str):
        return fix_text(value)
    return value

for col in cols_to_repair:
    texts_df[col] = texts_df[col].apply(repair_mojibake)

In [45]:
texts_df

,text_id_with_q,paragraph,question,answer_A,answer_B,answer_C,answer_D,rephrased_answer_A,onestopqa_question_id,article_id,paragraph_id,difficulty_level,article_batch,article_title
0,1_0_Adv_1_0,Leading water scientists have issued one of th...,"According to Malik Falkenmark's report, what w...",There will not be sufficient water to grow eno...,"By 2050, nine billion people will not have eno...","By 2050, animal-based protein consumption will...",Obesity rates around the world will rise,There won't be enough water to grow food for a...,0,0,1,Adv,1,NaN
1,1_0_Adv_2_0,"""There will be just enough water if the propor...",Which factor led to the increase in the price ...,Unfavorable weather conditions in different lo...,Instability of the international financial mar...,Warnings of water scarcity by Oxfam and the UN,Global warming,Bad weather in different locations on the planet,0,0,2,Adv,1,NaN
2,1_10_Adv_1_0,"Agios Efstratios is so remote, so forgotten by...",What event dramatically reduced the quality of...,The financial crisis that occurred in the country,A storm in the northern Aegean sea that devast...,The removal of ATM machines from the island,The installment of a new government,The national economic crisis,0,10,1,Adv,1,The Greek Island Where Time Is Running Out
3,1_10_Adv_1_1,"Agios Efstratios is so remote, so forgotten by...",What was true about tourism in Agios Efstratio...,A small number of tourists visited Agios Efstr...,Tourists overcrowded Agios Efstratios,Agios Efstratios was so remote that tourists w...,Many tourism agencies gave awards to Agios Efs...,A relatively small group of tourists visited t...,1,10,1,Adv,1,The Greek Island Where Time Is Running Out
4,1_10_Adv_1_2,"Agios Efstratios is so remote, so forgotten by...",Are there many hotels in Agios Efstratios?,"No, as there are only a small number of rooms ...","No, the beaches are empty of hotels","Yes, they are all in remote locations","Yes, the island has several 5-star resorts","No, the accommodation is limited to a small nu...",2,10,1,Adv,1,The Greek Island Where Time Is Running Out
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,3_9_Adv_3_1,SOHAY also runs sessions for parents and emplo...,What do Zhorna's brothers do?,They are both employed so that they can make m...,"One works at a restaurant and a club, and the ...",They try their best to not drop out of school ...,They help Zhorna with her homework after school,Both brothers have jobs to help their parents ...,1,9,3,Adv,3,Bangladeshi Organization Delivers a Lesson on ...
488,3_9_Adv_3_2,SOHAY also runs sessions for parents and emplo...,Why do Zhorna's brothers both work instead of ...,Their family is reliant on their salaries to m...,They prefer helping their parents,They found it too difficult to adapt to school,The nearest school is too far to commute to daily,Their family depends on the money they earn,2,9,3,Adv,3,Bangladeshi Organization Delivers a Lesson on ...
489,3_9_Adv_4_0,"In 2015, SOHAY helped 1,540 children to leave ...",What statistic does UNICEF provide about child...,1.3 million children are employed in unsafe wo...,4.7 million children are unable to attend school,"1,540 children were able to leave risky work i...",The children labor rates in Bangladesh are hig...,1.3 million children work in hazardous industries,1,9,4,Adv,3,Bangladeshi Organization Delivers a Lesson on ...
490,3_9_Adv_4_1,"In 2015, SOHAY helped 1,540 children to leave ...",What did SOHAY do in 2015?,"Assisted 2,125 children in attending school in...","Provided funds for 1,540 children in danger of...",Collaborated with UNICEF to reduce child labor,"Provided free classes for 3,000 children","Assisted 2,125 children in going to school rat...",0,9,4,Adv,3,Bangladeshi Organization Delivers a Lesson on ...
491,3_9_Adv_4_2,"In 2015, SOHAY helped 1,540 children to leave ...",How many children did SOHAY help leave work in...,"1,540","2,125",1.3 million,"10,000","1,540",2,9,4,Adv,3,Bangladeshi Organization Delivers a Lesson on ...

In [46]:
texts_df["article_batch"] = texts_df["article_batch"].astype(str).str.strip()

texts_batch_1 = texts_df[texts_df["article_batch"] == "1"].copy()
texts_batch_2 = texts_df[texts_df["article_batch"] == "2"].copy()
texts_batch_3 = texts_df[texts_df["article_batch"] == "3"].copy()

print("Batch 1:", len(texts_batch_1))
print("Batch 2:", len(texts_batch_2))
print("Batch 3:", len(texts_batch_3))
print("Total:", len(texts_batch_1) + len(texts_batch_2) + len(texts_batch_3))
print("Original:", len(texts_df))

Batch 1: 164
Batch 2: 164
Batch 3: 164
Total: 492
Original: 492

In [47]:
def clean_batch_articles(df):
    df = df.copy()

    # Normalize article_id to string for robust comparison
    article_id_str = df["article_id"].astype(str).str.strip()

    # Remove article_id 0 / article_0 / id_0
    df = df[~article_id_str.isin(["0", "article_0", "id_0"])].copy()

    # Recompute normalized article_id after filtering
    article_id_str = df["article_id"].astype(str).str.strip()

    # article_10 is the practice article
    df["practice"] = article_id_str.isin(["10", "article_10", "id_10"]).astype(int)

    return df


texts_batch_1 = clean_batch_articles(texts_batch_1)
texts_batch_2 = clean_batch_articles(texts_batch_2)
texts_batch_3 = clean_batch_articles(texts_batch_3)

In [48]:
texts_batch_1

,text_id_with_q,paragraph,question,answer_A,answer_B,answer_C,answer_D,rephrased_answer_A,onestopqa_question_id,article_id,paragraph_id,difficulty_level,article_batch,article_title,practice
2,1_10_Adv_1_0,"Agios Efstratios is so remote, so forgotten by...",What event dramatically reduced the quality of...,The financial crisis that occurred in the country,A storm in the northern Aegean sea that devast...,The removal of ATM machines from the island,The installment of a new government,The national economic crisis,0,10,1,Adv,1,The Greek Island Where Time Is Running Out,1
3,1_10_Adv_1_1,"Agios Efstratios is so remote, so forgotten by...",What was true about tourism in Agios Efstratio...,A small number of tourists visited Agios Efstr...,Tourists overcrowded Agios Efstratios,Agios Efstratios was so remote that tourists w...,Many tourism agencies gave awards to Agios Efs...,A relatively small group of tourists visited t...,1,10,1,Adv,1,The Greek Island Where Time Is Running Out,1
4,1_10_Adv_1_2,"Agios Efstratios is so remote, so forgotten by...",Are there many hotels in Agios Efstratios?,"No, as there are only a small number of rooms ...","No, the beaches are empty of hotels","Yes, they are all in remote locations","Yes, the island has several 5-star resorts","No, the accommodation is limited to a small nu...",2,10,1,Adv,1,The Greek Island Where Time Is Running Out,1
5,1_10_Adv_2_0,"But, because the island still runs on cash, th...",Why do Greek visitors no longer come to the is...,They do not have enough physical money,They can't afford the trip,It is 9 hours away from the closest island,Travel agents no longer recommend it as an att...,They don't have enough cash to travel there,1,10,2,Adv,1,The Greek Island Where Time Is Running Out,1
6,1_10_Adv_2_1,"But, because the island still runs on cash, th...",How has the closure of Greek banks affected th...,They have to make long trips to another island...,They have to go to the biggest Greek island fo...,Some have moved to Athens to earn more money,All the bank workers on the island lost their ...,They have to journey to another island to get ...,0,10,2,Adv,1,The Greek Island Where Time Is Running Out,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,1_9_Adv_5_1,"This might be why, he adds, the traditional ni...","According to Kelley, how will staggered starti...",They will be happier and healthier,They will find more creative solutions to prob...,People will be more synchronized and thus have...,They will have an easier time commuting to work,Workers' happiness and health will improve,1,9,5,Adv,1,Why You Should Start Work at 10AM,0
160,1_9_Adv_5_2,"This might be why, he adds, the traditional ni...","According to Kelley, how would staggered start...",Work would be done more effectively,Workspaces could stay open longer,More 50-year-olds would be employed,Lunch breaks would become shorter,Employees would perform their work more effici...,2,9,5,Adv,1,Why You Should Start Work at 10AM,0
161,1_9_Adv_6_0,There would probably be fewer accidents as dri...,How might staggered starting times for work af...,There would be no more rush hour,Rush hour would end earlier,Most traffic would occur later in the day,More people would be able to bike or walk,Rush hour traffic could disappear,0,9,6,Adv,1,Why You Should Start Work at 10AM,0
162,1_9_Adv_6_1,There would probably be fewer accidents as dri...,"How would later start times affect families, a...",It would be helpful since parents wouldn't hav...,Children and parents could wake up at the same...,There will be fewer accidents at home,Families will get to spend more time together,Families would benefit because parents would n...,1,9,6,Adv,1,Why You Should Start Work at 10AM,0
163,1_9_Adv_6_2,There would probably be fewer accidents as dri...,"According to Kelley, what creates difficulties...",Waking up their teenage kids,Waking up before their teenage kids,Driving in the morning,Not having enough personal time,Getting their teenage children out of bed,2,9,6,Adv,1,Why You Should Start Work at 10AM,0

In [49]:
def restrict_practice_questions(df):
    df = df.copy()

    # Robust numeric versions, in case these columns were read as strings
    paragraph_num = pd.to_numeric(df["paragraph_id"], errors="coerce")
    question_num = pd.to_numeric(df["onestopqa_question_id"], errors="coerce")

    # Keep all non-practice rows
    non_practice_mask = df["practice"] == 0

    # For practice rows, keep only:
    # paragraphs 1, 2, 3
    # question 0
    practice_keep_mask = (
        (df["practice"] == 1)
        & (paragraph_num.isin([1, 2, 3]))
        & (question_num == 0)
    )

    return df[non_practice_mask | practice_keep_mask].copy()


texts_batch_1 = restrict_practice_questions(texts_batch_1)
texts_batch_2 = restrict_practice_questions(texts_batch_2)
texts_batch_3 = restrict_practice_questions(texts_batch_3)

In [50]:
REGIMES = ["full knowledge", "partial knowledge", "no knowledge"]

ARTICLE_GROUPS = {
    "group_1": [1, 2, 3],
    "group_2": [4, 5, 6],
    "group_3": [7, 8, 9],
}

LATIN_SQUARE = [
    ["full knowledge", "partial knowledge", "no knowledge"],
    ["partial knowledge", "no knowledge", "full knowledge"],
    ["no knowledge", "full knowledge", "partial knowledge"],
]

LIST_NAMES = {
    1: "list_A",
    2: "list_B",
    3: "list_C",
}


def build_latin_square_lists_for_batch(df, batch_name):
    """
    Creates 3 experimental regime lists for one batch.

    Non-practice articles 1-9 are assigned to regimes by Latin square.
    Practice article 10 is duplicated into all regimes in every list.
    """

    df = df.copy()

    experimental_rows = df[df["practice"] == 0].copy()
    practice_rows = df[df["practice"] == 1].copy()

    all_list_parts = []

    for list_idx, regime_assignment in enumerate(LATIN_SQUARE, start=1):

        list_name = LIST_NAMES[list_idx]

        # 1. Add experimental articles according to Latin square
        for group_idx, (group_name, article_ids) in enumerate(ARTICLE_GROUPS.items()):

            regime = regime_assignment[group_idx]

            group_rows = experimental_rows[
                experimental_rows["article_id"].isin(article_ids)
            ].copy()

            group_rows["experiment_list"] = f"{batch_name}_{list_name}"
            group_rows["regime_list"] = list_name
            group_rows["regime"] = regime
            group_rows["article_group"] = group_name

            all_list_parts.append(group_rows)

        # 2. Duplicate practice rows into all three regimes
        for regime in REGIMES:
            practice_copy = practice_rows.copy()

            practice_copy["experiment_list"] = f"{batch_name}_{list_name}"
            practice_copy["regime_list"] = list_name
            practice_copy["regime"] = regime
            practice_copy["article_group"] = "practice"

            all_list_parts.append(practice_copy)

    batch_lists = pd.concat(all_list_parts, ignore_index=True)

    return batch_lists

In [51]:
batch_1_lists = build_latin_square_lists_for_batch(texts_batch_1, "batch_1")
batch_2_lists = build_latin_square_lists_for_batch(texts_batch_2, "batch_2")
batch_3_lists = build_latin_square_lists_for_batch(texts_batch_3, "batch_3")

In [52]:
experiment_lists_df = pd.concat(
    [batch_1_lists, batch_2_lists, batch_3_lists],
    ignore_index=True
)

overview = (
    experiment_lists_df
    .drop_duplicates(["experiment_list", "regime", "article_id"])
    .groupby(["experiment_list", "regime"])["article_id"]
    .apply(lambda x: sorted(x.astype(int).tolist()))
    .reset_index(name="article_ids")
)

overview

   experiment_list             regime    article_ids
0   batch_1_list_A     full knowledge  [1, 2, 3, 10]
1   batch_1_list_A       no knowledge  [7, 8, 9, 10]
2   batch_1_list_A  partial knowledge  [4, 5, 6, 10]
3   batch_1_list_B     full knowledge  [7, 8, 9, 10]
4   batch_1_list_B       no knowledge  [4, 5, 6, 10]
5   batch_1_list_B  partial knowledge  [1, 2, 3, 10]
6   batch_1_list_C     full knowledge  [4, 5, 6, 10]
7   batch_1_list_C       no knowledge  [1, 2, 3, 10]
8   batch_1_list_C  partial knowledge  [7, 8, 9, 10]
9   batch_2_list_A     full knowledge  [1, 2, 3, 10]
10  batch_2_list_A       no knowledge  [7, 8, 9, 10]
11  batch_2_list_A  partial knowledge  [4, 5, 6, 10]
12  batch_2_list_B     full knowledge  [7, 8, 9, 10]
13  batch_2_list_B       no knowledge  [4, 5, 6, 10]
14  batch_2_list_B  partial knowledge  [1, 2, 3, 10]
15  batch_2_list_C     full knowledge  [4, 5, 6, 10]
16  batch_2_list_C       no knowledge  [1, 2, 3, 10]
17  batch_2_list_C  partial knowledge  [7, 8, 9, 10]
18  batch_3_list_A     full knowledge  [1, 2, 3, 10]
19  batch_3_list_A       no knowledge  [7, 8, 9, 10]
20  batch_3_list_A  partial knowledge  [4, 5, 6, 10]
21  batch_3_list_B     full knowledge  [7, 8, 9, 10]
22  batch_3_list_B       no knowledge  [4, 5, 6, 10]
23  batch_3_list_B  partial knowledge  [1, 2, 3, 10]
24  batch_3_list_C     full knowledge  [4, 5, 6, 10]
25  batch_3_list_C       no knowledge  [1, 2, 3, 10]
26  batch_3_list_C  partial knowledge  [7, 8, 9, 10]

In [53]:
QUESTION_LATIN_SQUARE = {
    "q0": [0, 1, 2],
    "q1": [1, 2, 0],
    "q2": [2, 0, 1],
}


def add_question_lists_to_regime_lists(df):
    """
    Takes already regime-separated experiment lists and creates
    three question-list versions of each regime list.

    For non-practice rows:
    - keeps one question per article-paragraph
    - rotates question choice by paragraph position

    For practice rows:
    - keeps practice rows as they are
    - duplicates them into each question list
    """

    all_parts = []

    for question_list_name, question_assignment in QUESTION_LATIN_SQUARE.items():

        question_version = df.copy()

        non_practice = question_version[question_version["practice"] == 0].copy()
        practice = question_version[question_version["practice"] == 1].copy()

        # paragraph_id 1,2,3,... becomes repeating positions 0,1,2,0,1,2...
        paragraph_position = (non_practice["paragraph_id"] - 1) % 3

        selected_question = paragraph_position.map(
            {
                0: question_assignment[0],
                1: question_assignment[1],
                2: question_assignment[2],
            }
        )

        non_practice = non_practice[
            non_practice["onestopqa_question_id"] == selected_question
        ].copy()

        non_practice["question_list"] = question_list_name
        practice["question_list"] = question_list_name

        question_version_out = pd.concat(
            [non_practice, practice],
            ignore_index=True
        )

        question_version_out["final_experiment_list"] = (
            question_version_out["experiment_list"].astype(str)
            + "_"
            + question_list_name
        )

        all_parts.append(question_version_out)

    out = pd.concat(all_parts, ignore_index=True)

    return out

In [54]:
experiment_lists_df = add_question_lists_to_regime_lists(experiment_lists_df)

In [55]:
experiment_lists_df["final_experiment_list"].nunique()

27

In [56]:
experiment_lists_df

,text_id_with_q,paragraph,question,answer_A,answer_B,answer_C,answer_D,rephrased_answer_A,onestopqa_question_id,article_id,...,difficulty_level,article_batch,article_title,practice,experiment_list,regime_list,regime,article_group,question_list,final_experiment_list
0,1_1_Adv_1_0,"Unveiling a car with a top speed of 25mph, two...",What kind of reaction did Google's new driverl...,It drew strong attention from the industry,The industry wasn't impressed and did not find...,"It drew mostly excitement, but also disappoint...",It drew considerable skepticism from safety ex...,It sparked strong interest from the industry,0,1,...,Adv,1,Google Introduces its Driverless Car,0,batch_1_list_A,list_A,full knowledge,group_1,q0,batch_1_list_A_q0
1,1_1_Adv_2_0,"The car, in fact, takes over all the tasks of ...","According to the company's co-founder, the exp...",pleasant,forgettable,life-changing,thrilling,relaxing,1,1,...,Adv,1,Google Introduces its Driverless Car,0,batch_1_list_A,list_A,full knowledge,group_1,q0,batch_1_list_A_q0
2,1_1_Adv_3_2,Google says that the principal aim of the proj...,Could Google's cars be purchased at the time t...,"No, they needed to go through more tests","Yes, but only by signing up for a special test...","Yes, but only in Detroit","No, but it is possible to purchase the previou...","No, they still required further testing before...",2,1,...,Adv,1,Google Introduces its Driverless Car,0,batch_1_list_A,list_A,full knowledge,group_1,q0,batch_1_list_A_q0
3,1_1_Adv_4_1,One challenge is creating high-definition scan...,"Why are detailed, high-quality scans of the ro...",Because the cars cannot collect and process en...,Because people cannot collect and process enou...,Because California has thousands of miles of r...,Because the cars often don't arrive at their d...,Because the cars are unable to gather and proc...,0,1,...,Adv,1,Google Introduces its Driverless Car,0,batch_1_list_A,list_A,full knowledge,group_1,q0,batch_1_list_A_q0
4,1_1_Adv_5_1,But the prospect of driverless cars replacing ...,Approximately how many taxi drivers are there ...,"100,000","22,000","Unknown, as many drivers are not part of the U...","Almost none, as most are now working for Uber ...","100,000",1,1,...,Adv,1,Google Introduces its Driverless Car,0,batch_1_list_A,list_A,full knowledge,group_1,q0,batch_1_list_A_q0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1543,3_10_Adv_2_1,"""It was very surprising,"" Angela Erdmann, 62, ...",What did Angela's visitor deliver?,News of the discovery of the bottle,A message from the post office,A letter from a museum in Hamburg,A package for Angela,News that the bottle had been found,0,10,...,Adv,3,101-Year-Old Bottle Message,1,batch_3_list_C,list_C,partial knowledge,practice,q2,batch_3_list_C_q2
1544,3_10_Adv_3_0,"The brown beer bottle, which had been in the w...",How was the bottle discovered?,A fisherman discovered it,It washed up on the shore of Kiel,Holger von Neuhoff discovered it,A boy discovered it while playing in the sea,It was found by a fisherman,0,10,...,Adv,3,101-Year-Old Bottle Message,1,batch_3_list_C,list_C,partial knowledge,practice,q2,batch_3_list_C_q2
1545,3_10_Adv_1_0,Angela Erdmann never knew her grandfather. He ...,Who threw the bottle into the Baltic Sea?,Angela Erdmann's grandfather,Angela Erdmann,A museum worker,A fisherman,The bottle was thrown by Angela Erdmann's gran...,0,10,...,Adv,3,101-Year-Old Bottle Message,1,batch_3_list_C,list_C,no knowledge,practice,q2,batch_3_list_C_q2
1546,3_10_Adv_2_1,"""It was very surprising,"" Angela Erdmann, 62, ...",What did Angela's visitor deliver?,News of the discovery of the bottle,A message from the post office,A letter from a museum in Hamburg,A package for Angela,News that the bottle had been found,0,10,...,Adv,3,101-Year-Old Bottle Message,1,batch_3_list_C,list_C,no knowledge,practice,q2,batch_3_list_C_q2
1547,3_10_Adv_3_0,"The brown beer bottle, which had been in the w...",How was the bottle discovered?,A fisherman discovered it,It washed up on the shore of Kiel,Holger von Neuhoff discovered it,A boy discovered it while playing in the sea,It was found by a fisherman,0,10,...,Adv,3,101-Year-Old Bottle Message,1,batch_3_list_C,list_C,no knowledge,practice,q2,batch_3_list_C_q2

In [57]:
# Split the current 27 final lists into 27 separate dataframes

list_dfs = {
    list_name: df_list.copy()
    for list_name, df_list in experiment_lists_df.groupby("final_experiment_list")
}

print("Number of lists:", len(list_dfs))
print(sorted(list_dfs.keys()))

Number of lists: 27
['batch_1_list_A_q0', 'batch_1_list_A_q1', 'batch_1_list_A_q2', 'batch_1_list_B_q0', 'batch_1_list_B_q1', 'batch_1_list_B_q2', 'batch_1_list_C_q0', 'batch_1_list_C_q1', 'batch_1_list_C_q2', 'batch_2_list_A_q0', 'batch_2_list_A_q1', 'batch_2_list_A_q2', 'batch_2_list_B_q0', 'batch_2_list_B_q1', 'batch_2_list_B_q2', 'batch_2_list_C_q0', 'batch_2_list_C_q1', 'batch_2_list_C_q2', 'batch_3_list_A_q0', 'batch_3_list_A_q1', 'batch_3_list_A_q2', 'batch_3_list_B_q0', 'batch_3_list_B_q1', 'batch_3_list_B_q2', 'batch_3_list_C_q0', 'batch_3_list_C_q1', 'batch_3_list_C_q2']

In [58]:
import pandas as pd
from itertools import permutations
import random

REGIMES = ["full knowledge", "partial knowledge", "no knowledge"]

REGIME_ORDERINGS = {
    f"O{i}": list(order)
    for i, order in enumerate(permutations(REGIMES), start=1)
}

REGIME_ORDERINGS

{'O1': ['full knowledge', 'partial knowledge', 'no knowledge'],
 'O2': ['full knowledge', 'no knowledge', 'partial knowledge'],
 'O3': ['partial knowledge', 'full knowledge', 'no knowledge'],
 'O4': ['partial knowledge', 'no knowledge', 'full knowledge'],
 'O5': ['no knowledge', 'full knowledge', 'partial knowledge'],
 'O6': ['no knowledge', 'partial knowledge', 'full knowledge']}

In [59]:
def build_regime_order_assignment_table(experiment_lists_df, seed=42):
    """
    Builds the 54-list assignment table.

    For each batch/list combination, e.g. batch_1_list_A:
    - take q0, q1, q2 twice
    - randomly assign O1-O6 to them
    - produce 6 final ordered versions

    Across:
    3 batches x 3 regime lists x 6 orderings = 54 final lists.
    """

    rng = random.Random(seed)

    base_lists = sorted(experiment_lists_df["final_experiment_list"].unique())

    # Extract the base regime-list name by removing trailing _q0/_q1/_q2
    base_regime_lists = sorted(
        set(
            name.rsplit("_q", 1)[0]
            for name in base_lists
        )
    )

    rows = []

    for base_regime_list in base_regime_lists:

        q_versions = [
            f"{base_regime_list}_q0",
            f"{base_regime_list}_q1",
            f"{base_regime_list}_q2",
            f"{base_regime_list}_q0",
            f"{base_regime_list}_q1",
            f"{base_regime_list}_q2",
        ]

        order_labels = list(REGIME_ORDERINGS.keys())
        rng.shuffle(order_labels)

        for i, (source_list, order_label) in enumerate(zip(q_versions, order_labels), start=1):

            rows.append({
                "source_experiment_list": source_list,
                "order_label": order_label,
                "regime_order": REGIME_ORDERINGS[order_label],
                "ordered_experiment_list": f"{source_list}_{order_label}",
                "within_base_list_copy": i,
            })

    assignment_table = pd.DataFrame(rows)

    return assignment_table

In [60]:
regime_order_assignment = build_regime_order_assignment_table(
    experiment_lists_df,
    seed=42
)

regime_order_assignment

,source_experiment_list,order_label,regime_order,ordered_experiment_list,within_base_list_copy
0,batch_1_list_A_q0,O4,"[partial knowledge, no knowledge, full knowledge]",batch_1_list_A_q0_O4,1
1,batch_1_list_A_q1,O2,"[full knowledge, no knowledge, partial knowledge]",batch_1_list_A_q1_O2,2
2,batch_1_list_A_q2,O3,"[partial knowledge, full knowledge, no knowledge]",batch_1_list_A_q2_O3,3
3,batch_1_list_A_q0,O5,"[no knowledge, full knowledge, partial knowledge]",batch_1_list_A_q0_O5,4
4,batch_1_list_A_q1,O1,"[full knowledge, partial knowledge, no knowledge]",batch_1_list_A_q1_O1,5
5,batch_1_list_A_q2,O6,"[no knowledge, partial knowledge, full knowledge]",batch_1_list_A_q2_O6,6
6,batch_1_list_B_q0,O4,"[partial knowledge, no knowledge, full knowledge]",batch_1_list_B_q0_O4,1
7,batch_1_list_B_q1,O1,"[full knowledge, partial knowledge, no knowledge]",batch_1_list_B_q1_O1,2
8,batch_1_list_B_q2,O3,"[partial knowledge, full knowledge, no knowledge]",batch_1_list_B_q2_O3,3
9,batch_1_list_B_q0,O5,"[no knowledge, full knowledge, partial knowledge]",batch_1_list_B_q0_O5,4
10,batch_1_list_B_q1,O6,"[no knowledge, partial knowledge, full knowledge]",batch_1_list_B_q1_O6,5
11,batch_1_list_B_q2,O2,"[full knowledge, no knowledge, partial knowledge]",batch_1_list_B_q2_O2,6
12,batch_1_list_C_q0,O4,"[partial knowledge, no knowledge, full knowledge]",batch_1_list_C_q0_O4,1
13,batch_1_list_C_q1,O2,"[full knowledge, no knowledge, partial knowledge]",batch_1_list_C_q1_O2,2
14,batch_1_list_C_q2,O3,"[partial knowledge, full knowledge, no knowledge]",batch_1_list_C_q2_O3,3
15,batch_1_list_C_q0,O1,"[full knowledge, partial knowledge, no knowledge]",batch_1_list_C_q0_O1,4
16,batch_1_list_C_q1,O5,"[no knowledge, full knowledge, partial knowledge]",batch_1_list_C_q1_O5,5
17,batch_1_list_C_q2,O6,"[no knowledge, partial knowledge, full knowledge]",batch_1_list_C_q2_O6,6
18,batch_2_list_A_q0,O2,"[full knowledge, no knowledge, partial knowledge]",batch_2_list_A_q0_O2,1
19,batch_2_list_A_q1,O3,"[partial knowledge, full knowledge, no knowledge]",batch_2_list_A_q1_O3,2
20,batch_2_list_A_q2,O4,"[partial knowledge, no knowledge, full knowledge]",batch_2_list_A_q2_O4,3
21,batch_2_list_A_q0,O5,"[no knowledge, full knowledge, partial knowledge]",batch_2_list_A_q0_O5,4
22,batch_2_list_A_q1,O6,"[no knowledge, partial knowledge, full knowledge]",batch_2_list_A_q1_O6,5
23,batch_2_list_A_q2,O1,"[full knowledge, partial knowledge, no knowledge]",batch_2_list_A_q2_O1,6
24,batch_2_list_B_q0,O2,"[full knowledge, no knowledge, partial knowledge]",batch_2_list_B_q0_O2,1
25,batch_2_list_B_q1,O4,"[partial knowledge, no knowledge, full knowledge]",batch_2_list_B_q1_O4,2
26,batch_2_list_B_q2,O3,"[partial knowledge, full knowledge, no knowledge]",batch_2_list_B_q2_O3,3
27,batch_2_list_B_q0,O1,"[full knowledge, partial knowledge, no knowledge]",batch_2_list_B_q0_O1,4
28,batch_2_list_B_q1,O6,"[no knowledge, partial knowledge, full knowledge]",batch_2_list_B_q1_O6,5
29,batch_2_list_B_q2,O5,"[no knowledge, full knowledge, partial knowledge]",batch_2_list_B_q2_O5,6
30,batch_2_list_C_q0,O3,"[partial knowledge, full knowledge, no knowledge]",batch_2_list_C_q0_O3,1
31,batch_2_list_C_q1,O2,"[full knowledge, no knowledge, partial knowledge]",batch_2_list_C_q1_O2,2
32,batch_2_list_C_q2,O1,"[full knowledge, partial knowledge, no knowledge]",batch_2_list_C_q2_O1,3
33,batch_2_list_C_q0,O4,"[partial knowledge, no knowledge, full knowledge]",batch_2_list_C_q0_O4,4
34,batch_2_list_C_q1,O5,"[no knowledge, full knowledge, partial knowledge]",batch_2_list_C_q1_O5,5
35,batch_2_list_C_q2,O6,"[no knowledge, partial knowledge, full knowledge]",batch_2_list_C_q2_O6,6
36,batch_3_list_A_q0,O6,"[no knowledge, partial knowledge, full knowledge]",batch_3_list_A_q0_O6,1
37,batch_3_list_A_q1,O2,"[full knowledge, no knowledge, partial knowledge]",batch_3_list_A_q1_O2,2
38,batch_3_list_A_q2,O4,"[partial knowledge, no knowledge, full knowledge]",batch_3_list_A_q2_O4,3
39,batch_3_list_A_q0,O1,"[full knowledge, partial knowledge, no knowledge]",batch_3_list_A_q0_O1,4
40,batch_3_list_A_q1,O3,"[partial knowledge, full knowledge, no knowledge]",batch_3_list_A_q1_O3,5
41,batch_3_list_A_q2,O5,"[no knowledge, full knowledge, partial knowledge]",batch_3_list_A_q2_O5,6
42,batch_3_list_B_q0,O5,"[no knowledge, full knowledge, partial knowledge]",batch_3_list_B_q0_O5,1
43,batch_3_list_B_q1,O4,"[partial knowledge, no knowledge, full knowledge]",batch_3_list_B_q1_O4,2
44,batch_3_list_B_q2,O1,"[full knowledge, partial knowledge, no knowledge]",batch_3_list_B_q2_O1,3
45,batch_3_list_B_q0,O2,"[full knowledge, no knowledge, partial knowledge]",batch_3_list_B_q0_O2,4
46,batch_3_list_B_q1,O6,"[no knowledge, partial knowledge, full knowledge]",batch_3_list_B_q1_O6,5
47,batch_3_list_B_q2,O3,"[partial knowledge, full knowledge, no knowledge]",batch_3_list_B_q2_O3,6
48,batch_3_list_C_q0,O3,"[partial knowledge, full knowledge, no knowledge]",batch_3_list_C_q0_O3,1
49,batch_3_list_C_q1,O2,"[full knowledge, no knowledge, partial knowledge]",batch_3_list_C_q1_O2,2
50,batch_3_list_C_q2,O5,"[no knowledge, full knowledge, partial knowledge]",batch_3_list_C_q2_O5,3
51,batch_3_list_C_q0,O4,"[partial knowledge, no knowledge, full knowledge]",batch_3_list_C_q0_O4,4
52,batch_3_list_C_q1,O6,"[no knowledge, partial knowledge, full knowledge]",batch_3_list_C_q1_O6,5
53,batch_3_list_C_q2,O1,"[full knowledge, partial knowledge, no knowledge]",batch_3_list_C_q2_O1,6

In [61]:
print("Number of final ordered lists:", len(regime_order_assignment))
print(regime_order_assignment["ordered_experiment_list"].nunique())

Number of final ordered lists: 54
54

In [62]:
def apply_regime_order_assignments(experiment_lists_df, assignment_table):
    """
    Expands the current 27-list dataframe into 54 final ordered lists.

    Keeps all original columns from experiment_lists_df and only adds:
    - ordered_experiment_list
    - order_label
    - regime_order
    - regime_order_position
    """

    all_parts = []

    for _, assignment in assignment_table.iterrows():

        source_list = assignment["source_experiment_list"]
        ordered_list = assignment["ordered_experiment_list"]
        order_label = assignment["order_label"]
        regime_order = assignment["regime_order"]

        # IMPORTANT:
        # This keeps ALL columns from the original experiment_lists_df
        df_part = experiment_lists_df[
            experiment_lists_df["final_experiment_list"] == source_list
        ].copy()

        # Add ordering metadata
        df_part["ordered_experiment_list"] = ordered_list
        df_part["order_label"] = order_label
        df_part["regime_order"] = " -> ".join(regime_order)

        regime_position_map = {
            regime: position
            for position, regime in enumerate(regime_order, start=1)
        }

        df_part["regime_order_position"] = df_part["regime"].map(regime_position_map)

        all_parts.append(df_part)

    ordered_experiment_lists_df = pd.concat(all_parts, ignore_index=True)

    return ordered_experiment_lists_df

In [63]:
ordered_experiment_lists_df = apply_regime_order_assignments(
    experiment_lists_df,
    regime_order_assignment
)

In [64]:
original_cols = set(experiment_lists_df.columns)
new_cols = set(ordered_experiment_lists_df.columns)

print("Original columns:", len(original_cols))
print("New columns:", len(new_cols))

print("Lost columns:")
print(sorted(original_cols - new_cols))

print("Added columns:")
print(sorted(new_cols - original_cols))

Original columns: 21
New columns: 25
Lost columns:
[]
Added columns:
['order_label', 'ordered_experiment_list', 'regime_order', 'regime_order_position']

In [65]:
ordered_list_dfs = {
    list_name: df_list.copy()
    for list_name, df_list in ordered_experiment_lists_df.groupby("ordered_experiment_list")
}

print("Number of ordered list dataframes:", len(ordered_list_dfs))
print(sorted(ordered_list_dfs.keys()))

Number of ordered list dataframes: 54
['batch_1_list_A_q0_O4', 'batch_1_list_A_q0_O5', 'batch_1_list_A_q1_O1', 'batch_1_list_A_q1_O2', 'batch_1_list_A_q2_O3', 'batch_1_list_A_q2_O6', 'batch_1_list_B_q0_O4', 'batch_1_list_B_q0_O5', 'batch_1_list_B_q1_O1', 'batch_1_list_B_q1_O6', 'batch_1_list_B_q2_O2', 'batch_1_list_B_q2_O3', 'batch_1_list_C_q0_O1', 'batch_1_list_C_q0_O4', 'batch_1_list_C_q1_O2', 'batch_1_list_C_q1_O5', 'batch_1_list_C_q2_O3', 'batch_1_list_C_q2_O6', 'batch_2_list_A_q0_O2', 'batch_2_list_A_q0_O5', 'batch_2_list_A_q1_O3', 'batch_2_list_A_q1_O6', 'batch_2_list_A_q2_O1', 'batch_2_list_A_q2_O4', 'batch_2_list_B_q0_O1', 'batch_2_list_B_q0_O2', 'batch_2_list_B_q1_O4', 'batch_2_list_B_q1_O6', 'batch_2_list_B_q2_O3', 'batch_2_list_B_q2_O5', 'batch_2_list_C_q0_O3', 'batch_2_list_C_q0_O4', 'batch_2_list_C_q1_O2', 'batch_2_list_C_q1_O5', 'batch_2_list_C_q2_O1', 'batch_2_list_C_q2_O6', 'batch_3_list_A_q0_O1', 'batch_3_list_A_q0_O6', 'batch_3_list_A_q1_O2', 'batch_3_list_A_q1_O3', 'batch_3_list_A_q2_O4', 'batch_3_list_A_q2_O5', 'batch_3_list_B_q0_O2', 'batch_3_list_B_q0_O5', 'batch_3_list_B_q1_O4', 'batch_3_list_B_q1_O6', 'batch_3_list_B_q2_O1', 'batch_3_list_B_q2_O3', 'batch_3_list_C_q0_O3', 'batch_3_list_C_q0_O4', 'batch_3_list_C_q1_O2', 'batch_3_list_C_q1_O6', 'batch_3_list_C_q2_O1', 'batch_3_list_C_q2_O5']

In [66]:
for list_name in ordered_list_dfs:
    ordered_list_dfs[list_name] = (
        ordered_list_dfs[list_name]
        .sort_values(
            [
                "regime_order_position",
                "practice",
                "article_id",
                "paragraph_id",
            ]
        )
        .reset_index(drop=True)
    )

In [67]:
def keep_one_practice_question_per_regime_block(df):
    """
    For each final ordered list:
    - keep all non-practice rows
    - for practice rows, keep only one practice paragraph per regime block:
        block 1 gets the first practice paragraph
        block 2 gets the second practice paragraph
        block 3 gets the third practice paragraph

    This uses sorted practice paragraph_id values, so it works whether
    they are 0,1,2 or 1,2,3.
    """

    df = df.copy()

    all_parts = []

    for list_name, list_df in df.groupby("ordered_experiment_list"):

        non_practice = list_df[list_df["practice"] == 0].copy()
        practice = list_df[list_df["practice"] == 1].copy()

        # Get the available practice paragraphs in order
        practice_paragraphs = sorted(practice["paragraph_id"].unique())

        if len(practice_paragraphs) < 3:
            raise ValueError(
                f"{list_name} has fewer than 3 practice paragraphs: "
                f"{practice_paragraphs}"
            )

        # Map regime block position to practice paragraph
        # block 1 -> first practice paragraph
        # block 2 -> second practice paragraph
        # block 3 -> third practice paragraph
        block_to_practice_paragraph = {
            1: practice_paragraphs[0],
            2: practice_paragraphs[1],
            3: practice_paragraphs[2],
        }

        practice["target_practice_paragraph"] = practice["regime_order_position"].map(
            block_to_practice_paragraph
        )

        practice = practice[
            practice["paragraph_id"] == practice["target_practice_paragraph"]
        ].copy()

        practice = practice.drop(columns=["target_practice_paragraph"])

        all_parts.append(pd.concat([non_practice, practice], ignore_index=True))

    out = pd.concat(all_parts, ignore_index=True)

    return out

In [68]:
ordered_experiment_lists_df = keep_one_practice_question_per_regime_block(
    ordered_experiment_lists_df
)

In [69]:
practice_check = (
    ordered_experiment_lists_df[ordered_experiment_lists_df["practice"] == 1]
    .groupby(["ordered_experiment_list", "regime", "regime_order_position"])
    .agg(
        n_rows=("paragraph_id", "size"),
        practice_paragraphs=("paragraph_id", lambda x: sorted(x.unique())),
        question_ids=("onestopqa_question_id", lambda x: sorted(x.unique())),
    )
    .reset_index()
    .sort_values(["ordered_experiment_list", "regime_order_position"])
)

practice_check.head(30)

,ordered_experiment_list,regime,regime_order_position,n_rows,practice_paragraphs,question_ids
2,batch_1_list_A_q0_O4,partial knowledge,1,1,[1],[0]
1,batch_1_list_A_q0_O4,no knowledge,2,1,[2],[0]
0,batch_1_list_A_q0_O4,full knowledge,3,1,[3],[0]
4,batch_1_list_A_q0_O5,no knowledge,1,1,[1],[0]
3,batch_1_list_A_q0_O5,full knowledge,2,1,[2],[0]
5,batch_1_list_A_q0_O5,partial knowledge,3,1,[3],[0]
6,batch_1_list_A_q1_O1,full knowledge,1,1,[1],[0]
8,batch_1_list_A_q1_O1,partial knowledge,2,1,[2],[0]
7,batch_1_list_A_q1_O1,no knowledge,3,1,[3],[0]
9,batch_1_list_A_q1_O2,full knowledge,1,1,[1],[0]
10,batch_1_list_A_q1_O2,no knowledge,2,1,[2],[0]
11,batch_1_list_A_q1_O2,partial knowledge,3,1,[3],[0]
14,batch_1_list_A_q2_O3,partial knowledge,1,1,[1],[0]
12,batch_1_list_A_q2_O3,full knowledge,2,1,[2],[0]
13,batch_1_list_A_q2_O3,no knowledge,3,1,[3],[0]
16,batch_1_list_A_q2_O6,no knowledge,1,1,[1],[0]
17,batch_1_list_A_q2_O6,partial knowledge,2,1,[2],[0]
15,batch_1_list_A_q2_O6,full knowledge,3,1,[3],[0]
20,batch_1_list_B_q0_O4,partial knowledge,1,1,[1],[0]
19,batch_1_list_B_q0_O4,no knowledge,2,1,[2],[0]
18,batch_1_list_B_q0_O4,full knowledge,3,1,[3],[0]
22,batch_1_list_B_q0_O5,no knowledge,1,1,[1],[0]
21,batch_1_list_B_q0_O5,full knowledge,2,1,[2],[0]
23,batch_1_list_B_q0_O5,partial knowledge,3,1,[3],[0]
24,batch_1_list_B_q1_O1,full knowledge,1,1,[1],[0]
26,batch_1_list_B_q1_O1,partial knowledge,2,1,[2],[0]
25,batch_1_list_B_q1_O1,no knowledge,3,1,[3],[0]
28,batch_1_list_B_q1_O6,no knowledge,1,1,[1],[0]
29,batch_1_list_B_q1_O6,partial knowledge,2,1,[2],[0]
27,batch_1_list_B_q1_O6,full knowledge,3,1,[3],[0]

In [70]:
ordered_experiment_lists_df[ordered_experiment_lists_df['practice'] == 1][[ 'paragraph_id', 'regime_order', 'practice', 'regime', 'regime_order_position']]

,paragraph_id,regime_order,practice,regime,regime_order_position
47,3,partial knowledge -> no knowledge -> full know...,1,full knowledge,3
48,1,partial knowledge -> no knowledge -> full know...,1,partial knowledge,1
49,2,partial knowledge -> no knowledge -> full know...,1,no knowledge,2
97,2,no knowledge -> full knowledge -> partial know...,1,full knowledge,2
98,3,no knowledge -> full knowledge -> partial know...,1,partial knowledge,3
...,...,...,...,...,...
2719,2,full knowledge -> partial knowledge -> no know...,1,partial knowledge,2
2720,3,full knowledge -> partial knowledge -> no know...,1,no knowledge,3
2769,2,no knowledge -> full knowledge -> partial know...,1,full knowledge,2
2770,3,no knowledge -> full knowledge -> partial know...,1,partial knowledge,3
2771,1,no knowledge -> full knowledge -> partial know...,1,no knowledge,1

In [71]:
import numpy as np
import pandas as pd

answer_cols = ["answer_A", "answer_B", "answer_C", "answer_D"]

# 0 = answer_A, 1 = answer_B, 2 = answer_C, 3 = answer_D
rng = np.random.default_rng(seed=42) 

def randomize_answers(row):
    order = rng.permutation(4)  # e.g. [1, 0, 3, 2]

    # answers shown on screen in randomized order
    reordered_answers = {
        f"answer_{screen_pos}": row[answer_cols[original_answer_idx]]
        for screen_pos, original_answer_idx in enumerate(order)
    }

    # keys: where each original answer moved to
    # a_key = position of answer_A, b_key = position of answer_B, etc.
    inverse_order = np.empty(4, dtype=int)
    inverse_order[order] = np.arange(4)

    keys = {
        "a_key": inverse_order[0],
        "b_key": inverse_order[1],
        "c_key": inverse_order[2],
        "d_key": inverse_order[3],
    }

    return pd.Series({
        **reordered_answers,
        "correct_answer": inverse_order[0],   # where answer_A moved
        **keys,
        "answers_order": [int(x) for x in order],
    })

df_with_randomized_answers = ordered_experiment_lists_df.join(ordered_experiment_lists_df.apply(randomize_answers, axis=1))

In [72]:
df_with_randomized_answers['is_experimental'] = (df_with_randomized_answers['practice'] == 0).astype(int)

In [73]:
# ------------------------------------------------------------
# Sort final dataframe before saving
# ------------------------------------------------------------

df_with_randomized_answers = df_with_randomized_answers.copy()

# practice = 1 means practice row
# is_experimental = 0 for practice, 1 for experimental
df_with_randomized_answers["is_experimental"] = (
    df_with_randomized_answers["practice"] == 0
).astype(int)

# Make sure numeric sort columns are actually numeric
numeric_sort_cols = [
    "regime_order_position",
    "is_experimental",
    "article_id",
    "paragraph_id",
]

for col in numeric_sort_cols:
    df_with_randomized_answers[col] = pd.to_numeric(
        df_with_randomized_answers[col],
        errors="coerce"
    )

df_with_randomized_answers = (
    df_with_randomized_answers
    .sort_values(
        [
            "ordered_experiment_list",
            "regime_order_position",
            "is_experimental",
            "article_id",
            "paragraph_id",
        ],
        ascending=True,
    )
    .reset_index(drop=True)
)

In [79]:
df_with_randomized_answers

,text_id_with_q,paragraph,question,answer_A,answer_B,answer_C,answer_D,rephrased_answer_A,onestopqa_question_id,article_id,...,answer_1,answer_2,answer_3,correct_answer,a_key,b_key,c_key,d_key,answers_order,is_experimental
0,1_10_Adv_1_0,"Agios Efstratios is so remote, so forgotten by...",What event dramatically reduced the quality of...,The financial crisis that occurred in the country,A storm in the northern Aegean sea that devast...,The removal of ATM machines from the island,The installment of a new government,The national economic crisis,0,10,...,A storm in the northern Aegean sea that devast...,The financial crisis that occurred in the country,The installment of a new government,2,2,1,0,3,"[2, 1, 0, 3]",0
1,1_4_Adv_1_1,How far away are we from a world where drones ...,When does Amazon claim it will be ready to del...,Once the FFA releases their rules,Once the FFA approves Amazon's existing drones,Amazon says it is not sure when this will happen,Once the FFA regulations are approved by Congr...,As soon as the FAA establishes the regulations,0,4,...,Amazon says it is not sure when this will happen,Once the FFA releases their rules,Once the FFA regulations are approved by Congr...,2,2,0,1,3,"[1, 2, 0, 3]",1
2,1_4_Adv_2_0,"Professor Sanjiv Singh, who runs a cargo deliv...",What does Professor Singh think about fixing c...,He thinks that it is possible to resolve these...,He believes the problems might be too difficul...,He thinks that blocked GPS signals will be the...,He believes that his company will be the first...,He believes the problems can be overcome,1,4,...,He believes the problems might be too difficul...,He thinks that blocked GPS signals will be the...,He believes that his company will be the first...,0,0,1,2,3,"[0, 1, 2, 3]",1
3,1_4_Adv_3_2,One major problem is maintaining radio contact...,What will Huber's program enable drones to do?,Examine facilities like bridges and telephone ...,Fly more safely around certain dangerous areas,Identify interfering radio signals and antennas,Identify mountains and hills,Inspect infrastructure such as bridges and tel...,2,4,...,Identify mountains and hills,Fly more safely around certain dangerous areas,Identify interfering radio signals and antennas,0,0,2,3,1,"[0, 3, 1, 2]",1
4,1_4_Adv_4_1,"Huber said about Amazon: ""I have heard them sa...",What happens as you increase the distance a dr...,The drone becomes more dangerous to people,It's harder for the drone to spot dangers,It would be acceptable only if the drone has l...,The drone needs to fly faster,The risk to people increases,0,4,...,It would be acceptable only if the drone has l...,The drone becomes more dangerous to people,It's harder for the drone to spot dangers,2,2,3,1,0,"[3, 2, 0, 1]",1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2767,3_8_Adv_6_0,The ultranationalist leader of Russia's Libera...,What does Dmitry Medvedev say the incident shows?,That other places can be affected by similar i...,That Russia is less vulnerable than other part...,That the United States has been testing weapons,That more research about outer space is needed,Such dangers can threaten all parts of the world,1,8,...,That Russia is less vulnerable than other part...,That the United States has been testing weapons,That other places can be affected by similar i...,3,3,1,2,0,"[3, 1, 2, 0]",1
2768,3_9_Adv_1_2,The small space is set up to look like a class...,"Which children are referred to as ""lucky""?",Children who study in a tiny classroom,Children who found jobs after finishing school,Children who are able to concentrate,Children whose parents have jobs,Children learning in the small classroom,2,9,...,Children who found jobs after finishing school,Children whose parents have jobs,Children who study in a tiny classroom,3,3,1,0,2,"[2, 1, 3, 0]",1
2769,3_9_Adv_2_0,"For 14 years, SOHAY, a grassroots non-governme...",What do the classes at the center do?,Assist children with getting ready for primary...,Provide children additional homework,Teach children safety conditions for doing ris...,Provide childcare for children while their par...,The classes help children get ready for school,0,9,...,Teach children safety conditions for doing ris...,Assist children with getting ready for primary...,Provide children additional homework,2,2,3,1,0,"[3, 2, 0, 1]",1
2770,3_9_Adv_3_1,SOHAY also runs sessions for parents and emplo...,What do Zhorna's brothers do?,They are both employed so that they can make m...,"One works at a restaurant and a club, and the ...",They try their best to not drop out of school ...,They help Zhorna with her homework after school,Both brothers have jobs to help their parents ...,1,9,...,They try their best to not drop out of school ...,They are both employed so that they can make m...,"One works at a restaurant and a club, and the ...",2,2,3,1,0,"[3, 2, 0, 1]",1
2771,3_9_Adv_4_2,"In 2015, SOHAY helped 1,540 children to leave ...",How many children did SOHAY help leave work in...,"1,540","2,125",1.3 million,"10,000","1,540",2,9,...,"1,540","10,000","2,125",1,1,3,0,2,"[2, 0, 3, 1]",1

In [74]:
from pathlib import Path

# ------------------------------------------------------------
# Split randomized final dataframe by batch and save
# ------------------------------------------------------------

new_batched_dir = EXPERIMENT_DIR / "new_batched_lists"
new_batched_dir.mkdir(parents=True, exist_ok=True)

batch_dfs = {}

for batch_id in ["1", "2", "3"]:
    batch_name = f"batch_{batch_id}"

    batch_df = df_with_randomized_answers[
        df_with_randomized_answers["article_batch"] == batch_id
    ].copy()

    batch_dfs[batch_name] = batch_df

    batch_dir = new_batched_dir / batch_name
    batch_dir.mkdir(parents=True, exist_ok=True)

    csv_path = batch_dir / f"{batch_name}_lists.csv"
    tsv_path = batch_dir / f"{batch_name}_lists.tsv"

    batch_df.to_csv(csv_path, index=False, encoding="utf-8")
    batch_df.to_csv(tsv_path, index=False, sep="\t", encoding="utf-8")

    print(f"{batch_name}: {len(batch_df)} rows")
    print(f"  lists: {batch_df['ordered_experiment_list'].nunique()}")
    print(f"  saved CSV: {csv_path}")
    print(f"  saved TSV: {tsv_path}")

batch_1: 900 rows
  lists: 18
  saved CSV: E:\Technion\QA PROJECT\programming\QA_eyetracking_workspace\data\Experiment\new_batched_lists\batch_1\batch_1_lists.csv
  saved TSV: E:\Technion\QA PROJECT\programming\QA_eyetracking_workspace\data\Experiment\new_batched_lists\batch_1\batch_1_lists.tsv
batch_2: 954 rows
  lists: 18
  saved CSV: E:\Technion\QA PROJECT\programming\QA_eyetracking_workspace\data\Experiment\new_batched_lists\batch_2\batch_2_lists.csv
  saved TSV: E:\Technion\QA PROJECT\programming\QA_eyetracking_workspace\data\Experiment\new_batched_lists\batch_2\batch_2_lists.tsv
batch_3: 918 rows
  lists: 18
  saved CSV: E:\Technion\QA PROJECT\programming\QA_eyetracking_workspace\data\Experiment\new_batched_lists\batch_3\batch_3_lists.csv
  saved TSV: E:\Technion\QA PROJECT\programming\QA_eyetracking_workspace\data\Experiment\new_batched_lists\batch_3\batch_3_lists.tsv

In [75]:
# ------------------------------------------------------------
# Create SMALL_DEMO from batch_1
# ------------------------------------------------------------

def make_small_demo_from_batch(
    batch_df,
    n_articles_per_regime=2,
    n_paragraphs_per_article=2,
):
    """
    Create a small demo version from one batch.

    For each ordered_experiment_list and each regime:
    - keep the one practice trial for that regime
    - keep only the first n_articles_per_regime experimental articles
    - within those articles, keep only the first n_paragraphs_per_article paragraphs

    Assumes practice rows are already reduced to one practice row per regime block.
    """

    demo_parts = []

    for list_name, list_df in batch_df.groupby("ordered_experiment_list"):

        for regime, regime_df in list_df.groupby("regime"):

            # Keep practice trial for this regime
            practice_rows = regime_df[regime_df["practice"] == 1].copy()

            # Experimental rows only
            experimental_rows = regime_df[regime_df["practice"] == 0].copy()

            # Pick first N experimental articles in this regime
            selected_articles = sorted(experimental_rows["article_id"].unique())[
                :n_articles_per_regime
            ]

            experimental_rows = experimental_rows[
                experimental_rows["article_id"].isin(selected_articles)
            ].copy()

            # For each selected article, keep first N paragraphs
            keep_parts = []

            for article_id, article_df in experimental_rows.groupby("article_id"):

                selected_paragraphs = sorted(article_df["paragraph_id"].unique())[
                    :n_paragraphs_per_article
                ]

                article_keep = article_df[
                    article_df["paragraph_id"].isin(selected_paragraphs)
                ].copy()

                keep_parts.append(article_keep)

            if keep_parts:
                experimental_keep = pd.concat(keep_parts, ignore_index=True)
            else:
                experimental_keep = experimental_rows.iloc[0:0].copy()

            demo_parts.append(
                pd.concat([practice_rows, experimental_keep], ignore_index=True)
            )

    small_demo_df = pd.concat(demo_parts, ignore_index=True)

    return small_demo_df

In [80]:
batch_1_df = df_with_randomized_answers[
    df_with_randomized_answers["article_batch"] == "1"
].copy()

small_demo_df = make_small_demo_from_batch(
    batch_1_df,
    n_articles_per_regime=2,
    n_paragraphs_per_article=2,
)

# ------------------------------------------------------------
# Sort SMALL_DEMO before saving
# ------------------------------------------------------------

small_demo_df = small_demo_df.copy()

# Ensure is_experimental exists
# practice = 1 means practice row
# is_experimental = 0 for practice, 1 for experimental
small_demo_df["is_experimental"] = (
    small_demo_df["practice"] == 0
).astype(int)

# Make numeric sort columns numeric
numeric_sort_cols = [
    "regime_order_position",
    "is_experimental",
    "article_id",
    "paragraph_id",
]

for col in numeric_sort_cols:
    small_demo_df[col] = pd.to_numeric(
        small_demo_df[col],
        errors="coerce"
    )

small_demo_df = (
    small_demo_df
    .sort_values(
        [
            "ordered_experiment_list",
            "regime_order_position",
            "is_experimental",
            "article_id",
            "paragraph_id",
        ],
        ascending=True,
    )
    .reset_index(drop=True)
)

In [81]:


# ------------------------------------------------------------
# Save SMALL_DEMO
# ------------------------------------------------------------

small_demo_dir = EXPERIMENT_DIR / "new_batched_lists" / "SMALL_DEMO"
small_demo_dir.mkdir(parents=True, exist_ok=True)

small_demo_csv_path = small_demo_dir / "SMALL_DEMO_batch_1.csv"
small_demo_tsv_path = small_demo_dir / "SMALL_DEMO_batch_1.tsv"

small_demo_df.to_csv(small_demo_csv_path, index=False, encoding="utf-8")
small_demo_df.to_csv(small_demo_tsv_path, index=False, sep="\t", encoding="utf-8")

print("SMALL_DEMO rows:", len(small_demo_df))
print("SMALL_DEMO lists:", small_demo_df["ordered_experiment_list"].nunique())
print("Saved CSV:", small_demo_csv_path)
print("Saved TSV:", small_demo_tsv_path)

SMALL_DEMO rows: 270
SMALL_DEMO lists: 18
Saved CSV: E:\Technion\QA PROJECT\programming\QA_eyetracking_workspace\data\Experiment\new_batched_lists\SMALL_DEMO\SMALL_DEMO_batch_1.csv
Saved TSV: E:\Technion\QA PROJECT\programming\QA_eyetracking_workspace\data\Experiment\new_batched_lists\SMALL_DEMO\SMALL_DEMO_batch_1.tsv

In [82]:
small_demo_df[(small_demo_df["ordered_experiment_list"] == 'batch_1_list_A_q0_O4') & (small_demo_df["regime_order_position"] == 1)]

,text_id_with_q,paragraph,question,answer_A,answer_B,answer_C,answer_D,rephrased_answer_A,onestopqa_question_id,article_id,...,answer_1,answer_2,answer_3,correct_answer,a_key,b_key,c_key,d_key,answers_order,is_experimental
0,1_10_Adv_1_0,"Agios Efstratios is so remote, so forgotten by...",What event dramatically reduced the quality of...,The financial crisis that occurred in the country,A storm in the northern Aegean sea that devast...,The removal of ATM machines from the island,The installment of a new government,The national economic crisis,0,10,...,A storm in the northern Aegean sea that devast...,The financial crisis that occurred in the country,The installment of a new government,2,2,1,0,3,"[2, 1, 0, 3]",0
1,1_4_Adv_1_1,How far away are we from a world where drones ...,When does Amazon claim it will be ready to del...,Once the FFA releases their rules,Once the FFA approves Amazon's existing drones,Amazon says it is not sure when this will happen,Once the FFA regulations are approved by Congr...,As soon as the FAA establishes the regulations,0,4,...,Amazon says it is not sure when this will happen,Once the FFA releases their rules,Once the FFA regulations are approved by Congr...,2,2,0,1,3,"[1, 2, 0, 3]",1
2,1_4_Adv_2_0,"Professor Sanjiv Singh, who runs a cargo deliv...",What does Professor Singh think about fixing c...,He thinks that it is possible to resolve these...,He believes the problems might be too difficul...,He thinks that blocked GPS signals will be the...,He believes that his company will be the first...,He believes the problems can be overcome,1,4,...,He believes the problems might be too difficul...,He thinks that blocked GPS signals will be the...,He believes that his company will be the first...,0,0,1,2,3,"[0, 1, 2, 3]",1
3,1_5_Adv_1_0,"Illegal downloading is a kind of ""moral squalo...",Where does Philip Pullman hold a senior position?,"The ""Society of Authors""","The ""Index on Censorship""","The ""Association Against Illegal Downloading""","The ""Arts Union""",The Society of Authors,0,5,...,"The ""Association Against Illegal Downloading""","The ""Index on Censorship""","The ""Society of Authors""",3,3,2,1,0,"[3, 2, 1, 0]",1
4,1_5_Adv_2_1,"""The technical brilliance is so dazzling that ...",What does Pullman imply about artists?,They do not earn enough money for the amount o...,Their happiness is derived from their audience...,They can't see some of the moral issues with i...,They are unaware how often their works are pir...,They are underpaid for their work,1,5,...,They do not earn enough money for the amount o...,Their happiness is derived from their audience...,They are unaware how often their works are pir...,1,1,2,0,3,"[2, 0, 1, 3]",1

In [78]:
small_demo_df[(small_demo_df["ordered_experiment_list"] == 'batch_1_list_A_q0_O4')]

,text_id_with_q,paragraph,question,answer_A,answer_B,answer_C,answer_D,rephrased_answer_A,onestopqa_question_id,article_id,...,answer_1,answer_2,answer_3,correct_answer,a_key,b_key,c_key,d_key,answers_order,is_experimental
0,1_10_Adv_3_0,Kakali has badgered the government and a major...,How many tourists will likely visit the island...,"Fewer tourists, as indicated by the small numb...","More tourists, as all the hotels are already f...","Fewer tourists, since tourism is more expensiv...","More tourists, since the weather is forecasted...","A much smaller number of tourists, reflected i...",0,10,...,"Fewer tourists, since tourism is more expensiv...","More tourists, as all the hotels are already f...","Fewer tourists, as indicated by the small numb...",3,3,2,1,0,"[3, 2, 1, 0]",0
1,1_1_Adv_1_0,"Unveiling a car with a top speed of 25mph, two...",What kind of reaction did Google's new driverl...,It drew strong attention from the industry,The industry wasn't impressed and did not find...,"It drew mostly excitement, but also disappoint...",It drew considerable skepticism from safety ex...,It sparked strong interest from the industry,0,1,...,"It drew mostly excitement, but also disappoint...",The industry wasn't impressed and did not find...,It drew strong attention from the industry,3,3,2,1,0,"[3, 2, 1, 0]",1
2,1_1_Adv_2_0,"The car, in fact, takes over all the tasks of ...","According to the company's co-founder, the exp...",pleasant,forgettable,life-changing,thrilling,relaxing,1,1,...,life-changing,pleasant,forgettable,2,2,3,1,0,"[3, 2, 0, 1]",1
3,1_2_Adv_1_0,A nasal spray laced with the 'Love hormone' ox...,What difference did oxytocin make to the brain...,Improved responses to faces,Improved flow of chemicals in the brain,Increased responses to conversation,Increased activity when solving math problems,It improved how the brain reacts to faces,0,2,...,Improved responses to faces,Increased responses to conversation,Increased activity when solving math problems,1,1,0,2,3,"[1, 0, 2, 3]",1
4,1_2_Adv_2_0,Autism is a developmental disorder seen in mor...,What are the results of Oxytocin experiments s...,Some experiments found oxytocin had an effect ...,Experiments worked well on all participants bu...,They showed good results on more than 100 people,No experiments have been conducted so far,The results have been mixed,1,2,...,No experiments have been conducted so far,They showed good results on more than 100 people,Experiments worked well on all participants bu...,0,0,3,2,1,"[0, 3, 2, 1]",1
5,1_10_Adv_2_1,"But, because the island still runs on cash, th...",How has the closure of Greek banks affected th...,They have to make long trips to another island...,They have to go to the biggest Greek island fo...,Some have moved to Athens to earn more money,All the bank workers on the island lost their ...,They have to journey to another island to get ...,0,10,...,They have to make long trips to another island...,Some have moved to Athens to earn more money,All the bank workers on the island lost their ...,1,1,0,2,3,"[1, 0, 2, 3]",0
6,1_7_Adv_1_0,An octopus has made a brazen escape from the N...,Why does Yarrell mention that octopuses live a...,To provide evidence that Inky did not escape b...,To propose that Inky escaped because there wer...,To explain why Inky could only escape when no ...,To explain why octopuses are different from mo...,To show that loneliness was not the reason for...,0,7,...,To explain why Inky could only escape when no ...,To propose that Inky escaped because there wer...,To explain why octopuses are different from mo...,0,0,2,1,3,"[0, 2, 1, 3]",1
7,1_7_Adv_2_1,One theory is that Inky slid across the aquari...,What was the staff's reaction to Inky's disapp...,They were upset but did not search for him,"They were sad and launched a thorough search, ...",They examined a drainpipe that led directly to...,They were upset that they did not take adequat...,They were sad but chose not to look for him,1,7,...,They examined a drainpipe that led directly to...,"They were sad and launched a thorough search, ...",They were upset that they did not take adequat...,0,0,2,1,3,"[0, 2, 1, 3]",1
8,1_8_Adv_1_1,"Do you want your child to be good at sports, m...",What does the study say about the fitness of c...,They are weaker than children born in November...,"They are stronger than all children, except th...",They tend to be particularly good at sports,They tend to perform well on math and science ...,They are less fit than those born in November ...,0,8,...,They tend to perform well on math and science ...,"They are stronger than all children, except th...",They tend to be particularly good at sports,0,0,2,3,1,"[0, 3, 1, 2]",1
9,1_8_Adv_2_0,"The research involved 8,550 boys and girls age...",What were the study's conclusions concerning t...,November children ranked second in strength an...,November children scored highest in each category,November children came slightly behind Decembe...,November children did not differ from children...,"They placed first for stamina and power, and s...",1,8,...,November children scored highest in each category,November children ranked second in strength an...,November children came slightly behind Decembe...,2,2,1,3,0,"[3, 1, 0, 2]",1
10,1_10_Adv_1_0,"Agios Efstratios is so remote, so forgotten by...",What event dramatically reduced the quality of...,The financial crisis that occurred in the country,A storm in the northern Aegean sea that devast...,The removal of ATM machines from the island,The installment of a new government,The national economic crisis,0,10,...,A storm in the northern Aegean sea that devast...,The financial crisis that occurred in the country,The installment of a new government,2,2,1,0,3,"[2, 1, 0, 3]",0
11,1_4_Adv_1_1,How far away are we from a world where drones ...,When does Amazon claim it will be ready to del...,Once the FFA releases their rules,Once the FFA approves Amazon's existing drones,Amazon says it is not sure when this will happen,Once the FFA regulations are approved by Congr...,As soon as the FAA establishes the regulations,0,4,...,Amazon says it is not sure when this will happen,Once the FFA releases their rules,Once the FFA regulations are approved by Congr...,2,2,0,1,3,"[1, 2, 0, 3]",1
12,1_4_Adv_2_0,"Professor Sanjiv Singh, who runs a cargo deliv...",What does Professor Singh think about fixing c...,He thinks that it is possible to resolve these...,He believes the problems might be too difficul...,He thinks that blocked GPS signals will be the...,He believes that his company will be the first...,He believes the problems can be overcome,1,4,...,He believes the problems might be too difficul...,He thinks that blocked GPS signals will be the...,He believes that his company will be the first...,0,0,1,2,3,"[0, 1, 2, 3]",1
13,1_5_Adv_1_0,"Illegal downloading is a kind of ""moral squalo...",Where does Philip Pullman hold a senior position?,"The ""Society of Authors""","The ""Index on Censorship""","The ""Association Against Illegal Downloading""","The ""Arts Union""",The Society of Authors,0,5,...,"The ""Association Against Illegal Downloading""","The ""Index on Censorship""","The ""Society of Authors""",3,3,2,1,0,"[3, 2, 1, 0]",1
14,1_5_Adv_2_1,"""The technical brilliance is so dazzling that ...",What does Pullman imply about artists?,They do not earn enough money for the amount o...,Their happiness is derived from their audience...,They can't see some of the moral issues with i...,They are unaware how often their works are pir...,They are underpaid for their work,1,5,...,They do not earn enough money for the amount o...,Their happiness is derived from their audience...,They are unaware how often their works are pir...,1,1,2,0,3,"[2, 0, 1, 3]",1