In [10]:
from pathlib import Path
import sys
import os

PROJECT_ROOT = Path.cwd().parent

import pandas as pd

In [11]:
from src.data_paths import (
    GATHERERS_PROCESSED_PATH,
    HUNTERS_PROCESSED_PATH,
    DATA_DIR,
)

In [12]:
hunters = pd.read_csv(HUNTERS_PROCESSED_PATH)
gatherers = pd.read_csv(GATHERERS_PROCESSED_PATH)
all_participants = pd.concat([hunters, gatherers], ignore_index=True)

In [13]:
all_participants

,index,TRIAL_INDEX,participant_id,EYE_REPORTED,EYE_TRACKED,IA_AREA,IA_AVERAGE_FIX_PUPIL_SIZE,IA_BOTTOM,IA_DWELL_TIME,IA_DWELL_TIME_%,...,TFD_pure_outside,TFD_normalized_outside,RT_pure_distractor,RT_normalized_distractor,TFD_pure_distractor,TFD_normalized_distractor,RT_pure_critical,RT_normalized_critical,TFD_pure_critical,TFD_normalized_critical
0,0,4,l42_2070,RIGHT,Right,10165.0,NaN,261,0,0.0000,...,8325.0,105.379747,395.0,98.750000,370.0,92.500000,4937.0,329.133333,3144.0,209.600
1,1,4,l42_2070,RIGHT,Right,6099.0,2.705572,261,165,0.0280,...,8325.0,105.379747,395.0,98.750000,370.0,92.500000,4937.0,329.133333,3144.0,209.600
2,2,4,l42_2070,RIGHT,Right,14231.0,NaN,261,0,0.0000,...,8325.0,105.379747,395.0,98.750000,370.0,92.500000,4937.0,329.133333,3144.0,209.600
3,3,4,l42_2070,RIGHT,Right,28569.0,NaN,261,0,0.0000,...,8325.0,105.379747,395.0,98.750000,370.0,92.500000,4937.0,329.133333,3144.0,209.600
4,4,4,l42_2070,RIGHT,Right,4180.0,2.781068,492,184,0.0313,...,8325.0,105.379747,395.0,98.750000,370.0,92.500000,4937.0,329.133333,3144.0,209.600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760623,380273,65,l2_324,LEFT,Left,12535.0,NaN,1175,0,0.0000,...,3495.0,120.517241,1293.0,143.666667,642.0,71.333333,4355.0,108.875000,3255.0,81.375
760624,380274,65,l2_324,LEFT,Left,12768.0,NaN,1287,0,0.0000,...,3495.0,120.517241,1293.0,143.666667,642.0,71.333333,4355.0,108.875000,3255.0,81.375
760625,380275,65,l2_324,LEFT,Left,10640.0,2.500804,1287,403,0.0736,...,3495.0,120.517241,1293.0,143.666667,642.0,71.333333,4355.0,108.875000,3255.0,81.375
760626,380276,65,l2_324,LEFT,Left,6384.0,2.500804,1287,90,0.0164,...,3495.0,120.517241,1293.0,143.666667,642.0,71.333333,4355.0,108.875000,3255.0,81.375
760627,380277,65,l2_324,LEFT,Left,10752.0,NaN,1287,0,0.0000,...,3495.0,120.517241,1293.0,143.666667,642.0,71.333333,4355.0,108.875000,3255.0,81.375

In [17]:
text_cols = ["paragraph", "question", "answer_A", "answer_B", "answer_C", "answer_D"]

texts_per_qid = (
    all_participants.groupby("text_id_with_q")[text_cols].first().reset_index()
)
texts_per_qid

,text_id_with_q,paragraph,question,answer_A,answer_B,answer_C,answer_D
0,1_10_Adv_1_0,"Agios Efstratios is so remote, so forgotten by...",What event dramatically reduced the quality of...,The financial crisis that occurred in the country,A storm in the northern Aegean sea that devast...,The removal of ATM machines from the island,The installment of a new government
1,1_10_Adv_1_1,"Agios Efstratios is so remote, so forgotten by...",What was true about tourism in Agios Efstratio...,A small number of tourists visited Agios Efstr...,Tourists overcrowded Agios Efstratios,Agios Efstratios was so remote that tourists w...,Many tourism agencies gave awards to Agios Efs...
2,1_10_Adv_1_2,"Agios Efstratios is so remote, so forgotten by...",Are there many hotels in Agios Efstratios?,"No, as there are only a small number of rooms ...","No, the beaches are empty of hotels","Yes, they are all in remote locations","Yes, the island has several 5-star resorts"
3,1_10_Adv_2_0,"But, because the island still runs on cash, th...",Why do Greek visitors no longer come to the is...,They do not have enough physical money,They can't afford the trip,It is 9 hours away from the closest island,Travel agents no longer recommend it as an att...
4,1_10_Adv_2_1,"But, because the island still runs on cash, th...",How has the closure of Greek banks affected th...,They have to make long trips to another island...,They have to go to the biggest Greek island fo...,Some have moved to Athens to earn more money,All the bank workers on the island lost their ...
...,...,...,...,...,...,...,...
967,3_9_Ele_3_1,SOHAY also has classes for parents and employe...,What do Zhorna's brothers do?,They are both employed so that they can make m...,"One works at a restaurant and a club, and the ...",They try their best to not drop out of school ...,They help Zhorna with her homework after school
968,3_9_Ele_3_2,SOHAY also has classes for parents and employe...,Why do Zhorna's brothers both work instead of ...,Their family is reliant on their salaries to m...,They prefer helping their parents,They found it too difficult to adapt to school,The nearest school is too far to commute to daily
969,3_9_Ele_4_0,"In 2015, SOHAY helped 1,540 children to leave ...",What statistic does UNICEF provide about child...,1.3 million children are employed in unsafe wo...,4.7 million children are unable to attend school,"1,540 children were able to leave risky work i...",The children labor rates in Bangladesh are hig...
970,3_9_Ele_4_1,"In 2015, SOHAY helped 1,540 children to leave ...",What did SOHAY do in 2015?,"Assisted 2,125 children in attending school in...","Provided funds for 1,540 children in danger of...",Collaborated with UNICEF to reduce child labor,"Provided free classes for 3,000 children"
971,3_9_Ele_4_2,"In 2015, SOHAY helped 1,540 children to leave ...",How many children did SOHAY help leave work in...,"1,540","2,125",1.3 million,"10,000"

In [20]:
rephrasings = pd.read_csv(DATA_DIR / "experiment_text - with rephrasings.csv", encoding="utf-8")
texts_per_qid["rephrased_answer_A"] = rephrasings["rephrased_answer_A"].values

out_path = DATA_DIR / "experiment_text_completed.csv"
texts_per_qid.to_csv(out_path, index=False)
print(f"Saved {len(texts_per_qid)} rows to {out_path}")

Saved 972 rows to E:\QA PROJECT\programming\QA_eyetracking_workspace\data\experiment_text_completed.csv

In [19]:
texts_per_qid

,text_id_with_q,paragraph,question,answer_A,answer_B,answer_C,answer_D,rephrased_answer_A
0,1_10_Adv_1_0,"Agios Efstratios is so remote, so forgotten by...",What event dramatically reduced the quality of...,The financial crisis that occurred in the country,A storm in the northern Aegean sea that devast...,The removal of ATM machines from the island,The installment of a new government,The national economic crisis
1,1_10_Adv_1_1,"Agios Efstratios is so remote, so forgotten by...",What was true about tourism in Agios Efstratio...,A small number of tourists visited Agios Efstr...,Tourists overcrowded Agios Efstratios,Agios Efstratios was so remote that tourists w...,Many tourism agencies gave awards to Agios Efs...,A relatively small group of tourists visited t...
2,1_10_Adv_1_2,"Agios Efstratios is so remote, so forgotten by...",Are there many hotels in Agios Efstratios?,"No, as there are only a small number of rooms ...","No, the beaches are empty of hotels","Yes, they are all in remote locations","Yes, the island has several 5-star resorts","No, the accommodation is limited to a small nu..."
3,1_10_Adv_2_0,"But, because the island still runs on cash, th...",Why do Greek visitors no longer come to the is...,They do not have enough physical money,They can't afford the trip,It is 9 hours away from the closest island,Travel agents no longer recommend it as an att...,They don't have enough cash to travel there
4,1_10_Adv_2_1,"But, because the island still runs on cash, th...",How has the closure of Greek banks affected th...,They have to make long trips to another island...,They have to go to the biggest Greek island fo...,Some have moved to Athens to earn more money,All the bank workers on the island lost their ...,They have to journey to another island to get ...
...,...,...,...,...,...,...,...,...
967,3_9_Ele_3_1,SOHAY also has classes for parents and employe...,What do Zhorna's brothers do?,They are both employed so that they can make m...,"One works at a restaurant and a club, and the ...",They try their best to not drop out of school ...,They help Zhorna with her homework after school,Both brothers have jobs to help their parents ...
968,3_9_Ele_3_2,SOHAY also has classes for parents and employe...,Why do Zhorna's brothers both work instead of ...,Their family is reliant on their salaries to m...,They prefer helping their parents,They found it too difficult to adapt to school,The nearest school is too far to commute to daily,Their family depends on the money they earn
969,3_9_Ele_4_0,"In 2015, SOHAY helped 1,540 children to leave ...",What statistic does UNICEF provide about child...,1.3 million children are employed in unsafe wo...,4.7 million children are unable to attend school,"1,540 children were able to leave risky work i...",The children labor rates in Bangladesh are hig...,1.3 million children work in hazardous industries
970,3_9_Ele_4_1,"In 2015, SOHAY helped 1,540 children to leave ...",What did SOHAY do in 2015?,"Assisted 2,125 children in attending school in...","Provided funds for 1,540 children in danger of...",Collaborated with UNICEF to reduce child labor,"Provided free classes for 3,000 children","Assisted 2,125 children in going to school rat..."
971,3_9_Ele_4_2,"In 2015, SOHAY helped 1,540 children to leave ...",How many children did SOHAY help leave work in...,"1,540","2,125",1.3 million,"10,000","1,540"

In [8]:
from ftfy import fix_text
import pandas as pd

df = pd.read_csv(DATA_DIR / "experiment_text - with rephrasings.csv", encoding="latin1")

for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].map(lambda x: fix_text(x) if isinstance(x, str) else x)

df.to_csv(DATA_DIR / "experiment_text - with rephrasings.csv", index=False, encoding="utf-8")

C:\Users\deeth\AppData\Local\Temp\ipykernel_43128\709125255.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

In [9]:
test = pd.read_csv(DATA_DIR / "experiment_text - with rephrasings.csv", encoding="utf-8")
test

,ï»¿text_id_with_q,paragraph,question,answer_A,answer_B,answer_C,answer_D,rephrased_answer_A
0,1_10_Adv_1_0,"Agios Efstratios is so remote, so forgotten by...",What event dramatically reduced the quality of...,The financial crisis that occurred in the country,A storm in the northern Aegean sea that devast...,The removal of ATM machines from the island,The installment of a new government,The national economic crisis
1,1_10_Adv_1_1,"Agios Efstratios is so remote, so forgotten by...",What was true about tourism in Agios Efstratio...,A small number of tourists visited Agios Efstr...,Tourists overcrowded Agios Efstratios,Agios Efstratios was so remote that tourists w...,Many tourism agencies gave awards to Agios Efs...,A relatively small group of tourists visited t...
2,1_10_Adv_1_2,"Agios Efstratios is so remote, so forgotten by...",Are there many hotels in Agios Efstratios?,"No, as there are only a small number of rooms ...","No, the beaches are empty of hotels","Yes, they are all in remote locations","Yes, the island has several 5-star resorts","No, the accommodation is limited to a small nu..."
3,1_10_Adv_2_0,"But, because the island still runs on cash, th...",Why do Greek visitors no longer come to the is...,They do not have enough physical money,They can't afford the trip,It is 9 hours away from the closest island,Travel agents no longer recommend it as an att...,They don't have enough cash to travel there
4,1_10_Adv_2_1,"But, because the island still runs on cash, th...",How has the closure of Greek banks affected th...,They have to make long trips to another island...,They have to go to the biggest Greek island fo...,Some have moved to Athens to earn more money,All the bank workers on the island lost their ...,They have to journey to another island to get ...
...,...,...,...,...,...,...,...,...
967,3_9_Ele_3_1,SOHAY also has classes for parents and employe...,What do Zhorna's brothers do?,They are both employed so that they can make m...,"One works at a restaurant and a club, and the ...",They try their best to not drop out of school ...,They help Zhorna with her homework after school,Both brothers have jobs to help their parents ...
968,3_9_Ele_3_2,SOHAY also has classes for parents and employe...,Why do Zhorna's brothers both work instead of ...,Their family is reliant on their salaries to m...,They prefer helping their parents,They found it too difficult to adapt to school,The nearest school is too far to commute to daily,Their family depends on the money they earn
969,3_9_Ele_4_0,"In 2015, SOHAY helped 1,540 children to leave ...",What statistic does UNICEF provide about child...,1.3 million children are employed in unsafe wo...,4.7 million children are unable to attend school,"1,540 children were able to leave risky work i...",The children labor rates in Bangladesh are hig...,1.3 million children work in hazardous industries
970,3_9_Ele_4_1,"In 2015, SOHAY helped 1,540 children to leave ...",What did SOHAY do in 2015?,"Assisted 2,125 children in attending school in...","Provided funds for 1,540 children in danger of...",Collaborated with UNICEF to reduce child labor,"Provided free classes for 3,000 children","Assisted 2,125 children in going to school rat..."
971,3_9_Ele_4_2,"In 2015, SOHAY helped 1,540 children to leave ...",How many children did SOHAY help leave work in...,"1,540","2,125",1.3 million,"10,000","1,540"